server:
  port: 8001

#Mybatis 控制台打印SQL语句
logging:
  level:
    com.lcb.springcloud.learning: debug

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.lcb.springcloud.learning.po     # 所有po别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                     # mapper映射文件

spring:
  application:
    name: student-service-8001                              #服务注册到Eureka中的名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/mydb                   # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
    schema: classpath:sql/schema-mysql.sql                  #自动执行建表sql脚本，如果有多个sql文件，可以用逗号分隔
    data: classpath:sql/data-mysql.sql                      #自动执行初始化sql脚本
    #initialization-mode: always                             #Spring Boot2.x 必须添加 initialization-mode配置才会执行，默认为EMBEDDED也就是嵌入式数据库（H2这种），如果要在mysql下执行需要设置成为always

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://192.168.61.1:7001/eureka/,http://192.168.61.128:7002/eureka/
  instance:
    instance-id: student-service
    prefer-ip-address: true     #访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 30       #心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 90    #发呆时间，即服务续约到期时间（缺省为90s）

info:
  app.name: StudentService
  company.name: www.lcb.com
  company.address: www.lcb.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@
